import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rawData = JSON.parse(readFileSync(join(__dirname, 'icon-data-raw.json'), 'utf-8'));

const iconNames = Object.keys(rawData).sort();
const categories = [...new Set(Object.values(rawData).map(v => v.category).filter(Boolean))].sort();

// Ensure output directories exist
mkdirSync(join(__dirname, 'packages', 'core', 'src'), { recursive: true });
// Keep legacy output for backwards compat during migration
mkdirSync(join(__dirname, 'src', 'lib'), { recursive: true });

// --- Generate types.ts ---
const iconNameUnion = iconNames.map(n => `  | '${n}'`).join('\n');
const categoryUnion = categories.map(c => `  | '${c}'`).join('\n');

const coreTypesContent = `// Auto-generated by generate.mjs — do not edit manually
export type DooIconikName =
${iconNameUnion};

export type DooIconikSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

export type DooIconikCategory =
${categoryUnion};
`;

const legacyTypesContent = `// Auto-generated by generate.mjs — do not edit manually
export type DoodleIconName =
${iconNameUnion};

export type DoodleIconSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';

export type DoodleIconCategory =
${categoryUnion};
`;

// Write to packages/core/src/
writeFileSync(join(__dirname, 'packages', 'core', 'src', 'types.ts'), coreTypesContent);
console.log(`Generated packages/core/src/types.ts with ${iconNames.length} icon names and ${categories.length} categories`);

// Write legacy output to src/lib/
writeFileSync(join(__dirname, 'src', 'lib', 'types.ts'), legacyTypesContent);
console.log(`Generated src/lib/types.ts (legacy) with ${iconNames.length} icon names and ${categories.length} categories`);

// --- Generate icon-data.ts ---
const lines = [
  '// Auto-generated by generate.mjs — do not edit manually',
  '',
  'export interface IconData {',
  '  viewBox: string;',
  '  paths: string[];',
  '  circles?: { cx: number; cy: number; r: number }[];',
  '  lines?: { x1: number; y1: number; x2: number; y2: number }[];',
  '  stroke?: boolean;',
  '}',
  '',
  'export const iconData: Record<string, IconData> = {'
];

for (const name of iconNames) {
  const icon = rawData[name];
  const pathsStr = icon.paths.map(p => `      ${JSON.stringify(p)}`).join(',\n');

  lines.push(`  ${JSON.stringify(name)}: {`);
  lines.push(`    viewBox: ${JSON.stringify(icon.viewBox)},`);
  lines.push(`    paths: [`);
  lines.push(pathsStr);
  lines.push(`    ],`);

  if (icon.circles && icon.circles.length > 0) {
    const circlesStr = icon.circles.map(c => `      { cx: ${c.cx}, cy: ${c.cy}, r: ${c.r} }`).join(',\n');
    lines.push(`    circles: [`);
    lines.push(circlesStr);
    lines.push(`    ],`);
  }

  if (icon.lines && icon.lines.length > 0) {
    const linesStr = icon.lines.map(l => `      { x1: ${l.x1}, y1: ${l.y1}, x2: ${l.x2}, y2: ${l.y2} }`).join(',\n');
    lines.push(`    lines: [`);
    lines.push(linesStr);
    lines.push(`    ],`);
  }

  if (icon.stroke) {
    lines.push(`    stroke: true,`);
  }

  lines.push(`  },`);
}

lines.push('};');
lines.push('');

const iconDataContent = lines.join('\n');

// Write to packages/core/src/
writeFileSync(join(__dirname, 'packages', 'core', 'src', 'icon-data.ts'), iconDataContent);
console.log(`Generated packages/core/src/icon-data.ts with ${iconNames.length} icons`);

// Write legacy output to src/lib/
writeFileSync(join(__dirname, 'src', 'lib', 'icon-data.ts'), iconDataContent);
console.log(`Generated src/lib/icon-data.ts (legacy) with ${iconNames.length} icons`);
